# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'devazure-admin-grupo1-vm-s3-devops' # Este es un nombre que debe cambiar al que crearon.
  location: 'eastus2'
  resourceGroupName: 'GrupoRecursos-Grupo1-S3-DevOps' # Este es un nombre que debe cambiar al que crearon.
  virtualNetworkName: 'RedVirtual-Grupo1-S3-DevOps'
  subnetName: 'SubRed-Grupo1-S2DevOps'
  addressPrefix: '10.0.0.0/24'
  subnetPrefix: '10.0.0.0/26'
  securityGroupName: 'GrupoSeguridadRed-NSG-Grupo1-S3-DevOps'
  publicIpName: 'miVM-Grupo1-S3-DevOps-ip'
  vmName: 'miVM-Grupo1-S3-DevOps'
  vmSize: 'Standard_B1s'  # SKU disponible en eastus2
  adminUsername: 'user-s3-devops'
  adminPassword: 'Pass-s3-devops'  # Contraseña en texto plano (ajustar según necesidad)

  # Variables de la imagen
  imagePublisher: 'Canonical'
  imageOffer: '0001-com-ubuntu-server-jammy'
  imageSku: '22_04-lts-gen2'
  imageVersion: 'latest'  # Versión específica de la imagen

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -e  # Termina el script si cualquier comando falla

        # Crear un grupo de recursos
        echo "Creando grupo de recursos..."
        az group create --name $(resourceGroupName) --location "$(location)"
        echo "Grupo de recursos creado."

        # Crear una red virtual con un segmento de red
        echo "Creando red virtual..."
        az network vnet create \
          --resource-group $(resourceGroupName) \
          --name $(virtualNetworkName) \
          --address-prefix $(addressPrefix) \
          --subnet-name $(subnetName) \
          --subnet-prefix $(subnetPrefix)
        echo "Red virtual creada."
        az network vnet wait --resource-group $(resourceGroupName) --name $(virtualNetworkName) --created

        # Crear un grupo de seguridad de red
        echo "Creando grupo de seguridad de red..."
        az network nsg create --resource-group $(resourceGroupName) --name $(securityGroupName)
        echo "Grupo de seguridad de red creado."
        az network nsg wait --resource-group $(resourceGroupName) --name $(securityGroupName) --created

        # Permitir acceso a los puertos 22 y 80
        echo "Configurando reglas de NSG..."
        az network nsg rule create \
          --resource-group $(resourceGroupName) \
          --nsg-name $(securityGroupName) \
          --name AllowSSH \
          --protocol tcp \
          --direction inbound \
          --priority 1000 \
          --source-address-prefix '*' \
          --source-port-range '*' \
          --destination-address-prefix '*' \
          --destination-port-range 22 \
          --access allow

        az network nsg rule create \
          --resource-group $(resourceGroupName) \
          --nsg-name $(securityGroupName) \
          --name AllowHTTP \
          --protocol tcp \
          --direction inbound \
          --priority 1001 \
          --source-address-prefix '*' \
          --source-port-range '*' \
          --destination-address-prefix '*' \
          --destination-port-range 80 \
          --access allow

        az network nsg rule create \
          --resource-group $(resourceGroupName) \
          --nsg-name $(securityGroupName) \
          --name AllowICMP \
          --protocol icmp
