# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: DeployToVM
  jobs:
  - deployment: InstallApacheAndConfigure
    displayName: "Instalar y configurar apache"
    
    environment:
      name: "devazure-resource-admin-grupo1-vm-s3-devops"
      resourceType: VirtualMachine
      
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Iniciando la instalación de Apache2"
              sudo apt-get update
              sudo apt-get install -y apache2
              echo "Hola, configurado desde el pipeline la VM Grupo1 DevOps" | sudo tee /var/www/html/index.html
              sudo systemctl restart apache2
              echo "Instalación y configuracion completa"
            displayName: "Instalar Apache y configurar index.html"
